site_name:         Infinite Devops
description:       devops
home_banner_image_url: https://github.com/infinite-devops/infinite-devops.github.io/assets/3322836/f35c7cc1-4a0e-41a5-a898-bef52989e7d4
home_banner_title: What to listen here?
home_banner_paragraph: |
  Infinite DevOps is the podcast that helps you achieve understanding, 
  develop good practices, and check real use cases. 
  The show dives into what it takes to successfully develop, deliver and deploy 
  software in today's ever-changing business environment.
disqus_shortname:  jrichardsz-github-io
base_url:          https://podcastjs.github.io
about_us_paragraph: A site to share our day-to-day about devops

podcasters:
  jrichardsz:
    name:				JRichardsz
    avatar_image:			https://avatars.githubusercontent.com/u/3322836?v=4
    short_biography: Software Architect
    email:			you@email.com
    twitter_url:        https://twitter.com/JRichardsz
    github_url:         https://github.com/jrichardsz
    stackoverflow_url:  http://stackoverflow.com/users/3957754/jrichardsz
    youtube_url:        www.youtube.com/@JRichardsz
    blog_url:           https://jrichardsz.github.io

  bitmanuc:
    name:                               Manuel C.
    avatar_image:                       https://avatars.githubusercontent.com/u/31716953?s=96&v=4
    short_biography: Server Admin
    email:                      you@email.com
    #twitter_url:        https://twitter.com/JRichardsz
    github_url:         https://github.com/bitmanuc
    #stackoverflow_url:  http://stackoverflow.com/users/3957754/jrichardsz
    #youtube_url:        www.youtube.com/@JRichardsz
    blog_url:           https://bitmanuc.github.io/

